kind: Deployment
apiVersion: apps/v1
metadata:
  name: configmanager
  labels:
    app: "configmanager"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: configmanager
  template:
    metadata:
      labels:
        app: "configmanager"
    spec:
      containers:
        - name: main-container
          image: docker.io/nareshsaw5/configmanager:1.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: configmanager
  labels:
    app: configmanager
spec:
  type: NodePort
  selector:
    app: configmanager
  ports:
    - name: http
      port: 8080
      nodePort: 32080
